### ISSUE TITLE
tror inte det räcker med html och css för en tub asså

### ISSUE THREAD

**Issue by superfroggman** [linusromland/RomlandTubev2#1]
![dial](https://user-images.githubusercontent.com/49985901/96734923-4dcc9f80-13bb-11eb-9674-18f67938dc12.png)
![original](https://user-images.githubusercontent.com/49985901/96734942-5329ea00-13bb-11eb-85f3-7da5071af4a8.png)

**Comment by linusromland** [comment]
inte klar än okej?
